function parseBool(value, fallback) {
  if (value === undefined || value === null || value === "") return fallback;
  const v = String(value).trim().toLowerCase();
  if (v === "true" || v === "1" || v === "yes") return true;
  if (v === "false" || v === "0" || v === "no") return false;
  return fallback;
}

function parseIntSafe(value, fallback) {
  const n = parseInt(value, 10);
  return Number.isFinite(n) ? n : fallback;
}

function parseUsers(raw) {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch (e) {
    return [];
  }
}

exports.handler = async function () {
  const firebaseConfig = {
    apiKey: process.env.FIREBASE_API_KEY || "",
    authDomain: process.env.FIREBASE_AUTH_DOMAIN || "",
    projectId: process.env.FIREBASE_PROJECT_ID || "",
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET || "",
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || "",
    appId: process.env.FIREBASE_APP_ID || "",
    measurementId: process.env.FIREBASE_MEASUREMENT_ID || ""
  };

  const sheetsApiUrl = process.env.SHEETS_API_URL || "";
  const clientMode = process.env.CLIENT_MODE || "multi_company";
  const clientCompanyName = process.env.CLIENT_COMPANY_NAME || "";
  const authUsers = parseUsers(process.env.AUTH_USERS_JSON);

  const appConfig = {
    writeBufferMs: parseIntSafe(process.env.APP_WRITE_BUFFER_MS, 600000),
    dailyBackupEnabled: parseBool(process.env.APP_DAILY_BACKUP_ENABLED, true),
    monthlyCleanup: parseBool(process.env.APP_MONTHLY_CLEANUP, true),
    backupCheckIntervalMs: parseIntSafe(process.env.APP_BACKUP_CHECK_INTERVAL_MS, 3600000),
    clientMode,
    clientCompanyName
  };

  const body = [
    "// Runtime env generated by Netlify function",
    `window.FIREBASE_CONFIG = ${JSON.stringify(firebaseConfig)};`,
    `window.SHEETS_API_URL = ${JSON.stringify(sheetsApiUrl)};`,
    `window.CLIENT_MODE = ${JSON.stringify(clientMode)};`,
    `window.CLIENT_COMPANY_NAME = ${JSON.stringify(clientCompanyName)};`,
    `window.AUTH_USERS = ${JSON.stringify(authUsers)};`,
    `window.APP_CONFIG = ${JSON.stringify(appConfig)};`
  ].join("\n");

  return {
    statusCode: 200,
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "no-store, max-age=0"
    },
    body
  };
};
